<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Rewards
 */
?>
<?php
// @codingStandardsIgnoreFile

/**
 * @var \Amasty\Rewards\Block\Adminhtml\Sales\Creditmemo $block
 */
?>
<?php if ($block->canRefundRewardPoints()): ?>
    <div class="admin__field admin__field-option field-refund-reward-points">
        <label for="amasty_refund_reward_points" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Refund Reward Points')); ?></span>
        </label>
        <input type="text" class="input-text admin__control-text not-negative-amount" name="creditmemo[<?= \Amasty\Rewards\Block\Adminhtml\Sales\Creditmemo::REFUND_KEY ?>]"
               value="<?= /* @noEscape */ $block->getRefundRewardPointsBalance(); ?>" id="amasty_refund_reward_points">
        <div data-bind="<?= $block->getTooltipConfig() ?>" class="hidden">Current Customer Balance: <?= (float)$block->getCustomerRewardsBalance() ?> <strong>reward</strong> points.<br/>
            Reward Points to Base Currency Rate: <?= (float)$block->getRate() ?> points = 1.<br/>
            By default the customer will receive only points that were spent in the order, but you can add extra reward points or even cover all order by reward points, without money back.</div>
        <div class="tooltip" data-tooltip-trigger="rewards_tooltip"><span class="help"><span></span></div>
    </div>
<?php endif; ?>
