.rating-star__full,.rating-star__half,.rating-star__empty,.icon.f-fullstar,.icon.f-emptystar,.icon.f-halfstar{display:inline-block;font-family:FontAwesome;font-size:14px;color:#FFC800;margin-right:5px}
.rating-star__full:before,.f-fullstar:before{content:"\f005"}
.rating-star__half:before,.f-halfstar:before{content:"\f123"}
.rating-star__empty:before,.f-emptystar:before{content:"\f006"}
.rating-result__text, .reviews-actions, .rating-summary .label {display:none}
.page-title{margin-bottom:5px}
.product-review-list{margin:25px 0 0 0}
.product-review-summary h4{font-size:11px}
.amp-product-info-stock-sku{display: none;}
.review-toolbar{margin-top:15px}
.review-ratings .prod-rate-hld{display:inline-block;vertical-align:middle;margin-left:0;margin-top:-3px;}
.review-content{margin-top:10px;}
.review-title{font-size:15px;line-height:23px;margin-bottom:8px;color:#4f4f4f;}
.review-ratings .label{font-weight: 100;font-size: 13px;color:#a6a6a6;line-height: 23px;}
.special-price .price-label,
.old-price .price-label{display:none;}
.special-price, .old-price{display:block;}
.old-price .price{text-decoration:line-through;color:#b3b3b3;}
span[data-price-type="finalPrice"]{color:#f64e50;font-size:20px;}
.attribute.sku{font-size:12px;}
.amp-product-info-price{margin:15px 0 20px;padding:0 15px 0 0}
.qty-input{text-align:center;}
input[type="submit"],
.amp-product-addtocart a{text-align:center;display:block;background:#f64e50;line-height:60px;padding:0 50px;color:#fff;margin:24px 0 48px 0;font-size:15px;border-radius:7px;border:1px solid transparent;}
input[type="submit"]{width:100%;-webkit-appearance: none;}
input[type="submit"]:hover,
.amp-product-addtocart a:hover{background:#fff;color:#f64e50;text-decoration:none;border: 1px solid  #f2f2f2;}
.additional-attributes-wrapper{text-align:left;}
.additional-attributes-wrapper th,
.additional-attributes-wrapper td{vertical-align:top; font-weight: 100;font-size: 13px;}
.additional-attributes-wrapper .label{padding-right:7px;}
.additional-attributes-wrapper caption{text-align:left;background:#e6e6e6;padding:5px;}
.amp-product-items-block {margin:0 auto;text-align:center;width:60%}
.items-block-heading {font-size:14px;text-align:left;display:block;background:transparent;color:#4F4F4F;padding:14px 0;clear:both;outline:none;text-transform:uppercase;border-left:0;border-right:0;font-weight:700; text-align:center}
.items-block-heading .counter:before{content:'('}
.items-block-heading .counter:after{content:')'}
.amp-product-gallery{margin-top:30px;margin-bottom:30px}
#choose-options{width:100%}
.amp-product-items-block .item-detail {margin-top:15px;display:block}
.amp-product-items-block .item-detail .item-name {color: #000}
.amp-product-items-block .items-block-heading {font-size:16px}
.amp-product-media{min-height:330px}
.carousel-preview {display:flex;flex-wrap:wrap;align-items:center;justify-content:center;margin-top:30px;}
.carousel-preview button {min-width:60px;margin:0;padding:0;background:#F2F2F2;height: 100px;}
.carousel-preview button:active { opacity:0.5;}
.review-item{border-bottom:1px solid #a9a9a9;margin-top:15px;}
.review-details{margin:13px 0 10px 0}
.review-details p{font-size: 12px;margin: 0;display: inline-block;color:#a6a6a6;}
#amp-review-form .input-text{width:100%;}
#amp-review-form div.field{margin-bottom:10px}
#amp-review-form #amp-review-form-submit{margin-top:0}
.amp-product-details-tabs{padding:20px 0px;clear:both;width:100%}
.amp-product-details-tabs #product-data-tabs > section:last-child{border-bottom:1px solid #dfdfdf}
#product-data-tabs .tab-content{padding:10px 0}
#product-data-tabs .table-caption{display:none;}
#product-data-tabs section header.items-block-heading:before{content:"\f106";display:inline-block;vertical-align:middle;position:absolute;right:11px;top:15px;font-size: 14px;color:#000;font-family:"FontAwesome"}
#product-data-tabs section header.items-block-heading[aria-expanded="false"]{border-bottom: 0;}
#product-data-tabs section header.items-block-heading[aria-expanded="true"]:before{transform:rotate(180deg);}
#product-data-tabs section header.items-block-heading[aria-expanded="true"]:after{transform:rotate(180deg);top:19px;}
#product-data-tabs section header.items-block-heading:before,
#product-data-tabs section header.items-block-heading:after{left: auto;right: 11px;}
.review-fieldset,.review-field-ratings{border:0;margin:0;padding:0;}
.review-field-ratings{margin-top:15px;}
.review-field-text textarea{width:100%;box-sizing:border-box;}
.review-legend + br{display:none;}
.icon-digit{font-weight: 400;font-size: 11px;}
@media (max-width:769px){
.amp-product-info-stock-sku{margin-top:-48px}
}
@media (max-width:400px){
.amp-product-media,.amp-product-details-tabs{min-height:0}
}
.amp-product-details .page-title {text-transform: none;font-size:24px;line-height:32px;color:#000;}