<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Catalog image grid amp widget template
 *
 */
?>

<?php
$category = $block->getCategory();
$showImageInCategory = $block->getImageCategories();
$showImageInSubcategory = $block->getImageSubcategories();
$imageType = $block->getImageType();
$categoryToShow = $block->getAmountCategories();
$subCategoryToShow = $block->getAmountSubcategories();
$imageWidth = $block->getImageWidth();
$columnsCount = $block->getColumnsCount();
$categories = $block->getChildrens($category);
$iconSize = $block->getIconSize();
$viewMore = $block->getViewMore();
$viewMoreText = $block->getViewMoreText();
$ampImgWidth = $block->getCigImgWidth();
$ampImgHeight = $block->getCigImgHeight();
?>

<div class='catalog-image-grid category-id-<?= /* @escapeNotVerified */ $category->getId(); ?> <?= /* @escapeNotVerified */ $block->getCssClass(); ?>'>
    <?php if ($block->getTitle()): ?>
        <div class='block-title'><strong><?= /* @escapeNotVerified */ $block->getTitle(); ?></strong></div>
    <?php endif; ?>
    <ul class='category-grid columns-<?= /* @escapeNotVerified */ $columnsCount; ?>'>
        <?php $categoryNum = 1; ?>
        <?php foreach ($categories as $rootCategory): ?>
            <?php
                if ($categoryNum > $categoryToShow) break;
                $categoryNum++;
                $categoryFontIcon = $rootCategory->getIconClass();
            ?>

            <li>
                <div class='grid-inner'>
                    <a href='<?= /* @escapeNotVerified */ $rootCategory->getUrl(); ?>' class='category-link'>
                        <?php if ($showImageInCategory && $categoryFontIcon && $imageType == 'font_icon'): ?>
                            <i class='category-icon <?= /* @escapeNotVerified */ $categoryFontIcon; ?>'></i>
                        <?php endif; ?>
                        <span class="category-name"><?= /* @escapeNotVerified */ $rootCategory->getName(); ?></span>
                        <?php if ($showImageInCategory && $block->getImageByType($rootCategory,$imageType)): ?>
                            <span class='category-image'>
                                <amp-img alt='catalog-image-grid'
                                         width='<?= /* @escapeNotVerified */ $ampImgWidth; ?>'
                                         height='<?= /* @escapeNotVerified */ $ampImgHeight; ?>' layout='responsive'
                                         src='<?= /* @escapeNotVerified */ $block->getImageByType($rootCategory, $imageType); ?>'>
                                </amp-img>
                            </span>
                        <?php endif; ?>
                    </a>

                    <?php
                        $subCategoryNum = 1;
                        $subCategories = $block->getChildrens($rootCategory);
                    ?>
                    <div class='inner'>
                        <ul class='subcategory-grid'>
                            <?php foreach ($subCategories as $subCategory): ?>
                                <?php
                                    if ($subCategoryNum > $subCategoryToShow) break;
                                    $subCategoryNum++;
                                    $subCategoryFontIcon = $subCategory->getIconClass();
                                ?>
                                <li>
                                    <a href='<?= /* @escapeNotVerified */ $subCategory->getUrl(); ?>' class='subcategory-link'>
                                        <?php if ($showImageInSubcategory && $block->getImageByType($subCategory,$imageType)): ?>
                                            <span class='subcategory-image'>
                                                <amp-img alt='catalog-image-grid'
                                                         width='<?= /* @escapeNotVerified */ $ampImgWidth; ?>'
                                                         height='<?= /* @escapeNotVerified */ $ampImgHeight; ?>' layout='responsive'
                                                         src='<?= /* @escapeNotVerified */ $block->getImageByType($subCategory, $imageType); ?>'>
                                                </amp-img>
                                            </span>
                                        <?php endif; ?>
                                        <?php if ($showImageInSubcategory && $subCategoryFontIcon && $imageType == 'font_icon'): ?>
                                            <i class='category-icon <?= /* @escapeNotVerified */ $subCategoryFontIcon; ?>'></i>
                                        <?php endif; ?>
                                        <span class="subcategory-name"><?= /* @escapeNotVerified */ $subCategory->getName(); ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <?php if ($viewMore && $subCategoryNum > $subCategoryToShow): ?>
                            <a href='<?= /* @escapeNotVerified */ $rootCategory->getUrl(); ?>' class='button-more'><?= /* @escapeNotVerified */ __($viewMoreText ?: sprintf('View more in %s', $rootCategory->getName())) ?></a>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
