<?php
$columnNumber = 3;

$dateFormat = $this->getDateFormat();
?>

<?php if ($posts = $this->getPosts()) : ?>
    <div class="block widget blog-posts widget-post-column">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php echo __($block->getTitle()) ?></strong>
            </div>
        <?php endif; ?>

        <div class="block-content">
            <div class="post-items">
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <?php if ($image = $post->getImage()): ?>
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img alt="" src="<?php echo $image ?>" /></a>
                        </div>
                        <?php endif; ?>

                        <div class="post-content-wrapper">
                            <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>

                            <!-- Title -->
                            <div class="post-title">
                                <h6>
                                    <a href="<?php echo $this->getPostUrl($post); ?>">
                                        <?php echo $block->getStringTruncated($post->getTitle(), $block->getPostTitleLength()) ?>
                                    </a>
                                </h6>
                            </div>

                            <!-- Short Description -->
                            <div class="post-short-content">
                                <?php echo $block->filterContent($block->getStringTruncated($post->getShortContent(), $block->getPostDescLength())); ?>
                            </div>

                            <?php if ($post->getCommentsEnabled()) : ?>
                                <span class="post-comments">
                                    <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                        <span class="count"><?php echo $post->getApprovedComments()->count(); ?></span> <?php echo __('comments'); ?>
                                    </a>
                                </span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>