<?php
/** @var \Zemez\Blog\Block\Widget\PostList $block */
$dateFormat = $this->getDateFormat();
if ($block->isEnabledCarousel()) {
    $itemWidth = "";
} else {
    $itemWidth = $block->getPostAmountPerRow() ? sprintf('flex-basis: %1$.2f%%; -webkit-flex-basis: %1$.2f%%; max-width: %1$.2f%%;', 100 / $block->getPostAmountPerRow()) : '';
}
?>
<?php $id_my_widget = rand(1,100); ?>
<?php if(!$block->isEnabledCarousel()): ?>
<style>
    @media (min-width: 991px) {
        .id-<?php echo $id_my_widget; ?> .post-items > .post-item {
            <?php echo $itemWidth ?>
        }
    }
</style>
 <?php endif;  ?>

<?php if ($posts = $this->getPosts()) : ?>
    <div class="block widget blog-posts widget-post-grid id-<?php echo $id_my_widget; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php echo __($block->getTitle()) ?></strong>
        </div>
        <div class="block-content">
            <div class="post-items<?php if ($block->isEnabledCarousel()): ?> owl-carousel<?php endif; ?>"<?php if ($block->isEnabledCarousel()): ?> data-mage-init='{"blogCarousel": { "responsive": { "1200": { "items" : "<?php /* @escapeNotVerified */ echo $block->getPostAmountPerView(); ?>" }}}}'<?php endif; ?>>
            <?php foreach ($posts as $post): ?>
                <div class="post-item">
                    <div class="item-wrapper">
                        <!-- Image -->
                        <?php if ($image = $post->getImage()): ?>
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img alt="" src="<?php echo $image ?>" /></a>
                        </div>
                        <?php endif; ?>

                        <div class="post-content-wrapper">
                            <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>

                            <!-- Title -->
                            <div class="post-title">
                                <h6>
                                    <a href="<?php echo $this->getPostUrl($post); ?>">
                                        <?php echo $block->getStringTruncated($post->getTitle(), $block->getPostTitleLength()) ?>
                                    </a>
                                </h6>
                            </div>

                            <!-- Short Description -->
                            <div class="post-short-content">
                                <?php echo $block->filterContent($block->getStringTruncated($post->getShortContent(), $block->getPostDescLength())); ?>
                            </div>

                            <?php if ($post->getCommentsEnabled()) : ?>
                                <span class="post-comments">
                                        <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                            <span class="count"><?php echo $post->getApprovedComments()->count(); ?></span> <?php echo __('comments'); ?>
                                        </a>
                                    </span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
            <a href="<?php /* @escapeNotVerified */ echo $this->getUrl() . "blog" ?>" class="action primary"><?php echo __('See all posts'); ?></a>
        </div>
    </div>
<?php endif; ?>