<?php
$postCollection = $block->getCollection();
$dateFormat = $this->getDateFormat();

if(!$postCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('There are no posts matching the selection.') ?></div>
    </div>
<?php else: ?>
<div class="posts-list-wrapper">
    <div class="toolbar-top">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
    <div class="block-posts-list">
        <ol class="post-items">
            <?php foreach($postCollection as $post): ?>
                <li class="post-item" data-post-id="<?php echo $post->getPostId(); ?>">
                    <div class="item-wrapper">

                        <!-- Image -->
                        <?php if ($image = $post->getImage()): ?>
                        <div class="post-image">
                            <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $image ?>" /></a>
                        </div>
                        <?php endif; ?>

                        <div class="post-content-wrapper">
                            <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                            <!-- Title -->
                            <div class="post-title">
                                <h6><a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a></h6>
                            </div>
                            <!-- Short Description -->
                            <div class="post-short-content">
                                <?php echo $block->filterContent($post->getShortContent()); ?>
                            </div>

                            <?php if ($post->getCommentsEnabled()) : ?>
                                <span class="post-comments">
                                    <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                        <span class="count"><?php echo $post->getApprovedComments()->count(); ?></span> <?php echo __('comments'); ?>
                                    </a>
                                </span>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
</div>
<?php endif; ?>